development:
  adapter: postgresql
  encoding: unicode
  database: isaac10ui_demo_test
  pool: 5
  username: isaac10
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: isaac10ui_demo_test
  pool: 5
  username: isaac10
  password:
